# Generated by Django 4.0.5 on 2022-06-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_building_acronym_building_active_room_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='number',
        ),
        migrations.AddField(
            model_name='building',
            name='internal_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
