# Generated by Django 4.0.5 on 2022-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_building_acronym'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('number', 'building'), name='unique_room_per_building'),
        ),
    ]
