# Generated by Django 4.0.5 on 2022-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_google_id_alter_device_google_enrollment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_enrollment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='google_last_policy_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
