# Generated by Django 4.0.5 on 2022-06-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_building_acronym_building_active_room_active'),
        ('devices', '0004_devicestatus_device_room_device_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'verbose_name_plural': 'Device statuses'},
        ),
        migrations.AddField(
            model_name='device',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.building'),
        ),
    ]
