# Generated by Django 4.0.5 on 2022-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicestatus_options_device_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
