# Generated by Django 4.0.5 on 2022-06-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0020_alter_googledevicemapping_device_field'),
        ('devices', '0006_alter_device_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='google_sync_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='googlesync.googledevicesyncprofile'),
        ),
    ]
