# Generated by Django 4.0.5 on 2022-06-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
