# Generated by Django 4.0.5 on 2022-06-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
