# Generated by Django 4.0.5 on 2022-07-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_deviceaccessory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='asset_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
