# Generated by Django 4.0.5 on 2022-07-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_google_id'),
        ('devices', '0009_alter_devicemodel_manufacturer'),
        ('devices', '0011_alter_deviceaccessory_name'),
    ]

    operations = [
    ]
