# Generated by Django 4.0.5 on 2022-07-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0022_googledevice_alter_googledevicemapping_device_field'),
        ('devices', '0013_remove_device_google_sync_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='google_enrollment_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_last_policy_sync',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_most_recent_user',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_organization_unit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='google_status',
        ),
        migrations.AddField(
            model_name='device',
            name='google_device',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='googlesync.googledevice'),
        ),
    ]
