# Generated by Django 4.0.5 on 2022-07-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0022_googledevice_alter_googledevicemapping_device_field'),
        ('devices', '0014_remove_device_google_enrollment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_device',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='googlesync.googledevice'),
        ),
    ]
