# Generated by Django 4.0.5 on 2022-07-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_devicestatus_is_inactive_alter_device_asset_id'),
        ('devices', '0015_alter_device_google_device'),
    ]

    operations = [
    ]
