# Generated by Django 4.0.5 on 2022-07-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0031_alter_googledevice_annotated_asset_id_and_more'),
        ('devices', '0016_merge_20220710_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_device',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='googlesync.googledevice'),
        ),
    ]
