# Generated by Django 4.0.5 on 2022-07-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0039_alter_googledevice_device_model_and_more'),
        ('devices', '0017_alter_device_google_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='google_device',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='googlesync.googledevice'),
        ),
    ]
