# Generated by Django 4.0.5 on 2022-07-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_device_google_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceaccessory',
            options={'verbose_name_plural': 'Device accessories'},
        ),
    ]
