# Generated by Django 4.0.7 on 2022-09-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_devicemodel_unique_manufacturer_and_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ImageField(upload_to='uploads/devicetag/')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='devices', to='devices.devicetag'),
        ),
    ]
