# Generated by Django 4.0.7 on 2022-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_devicetag_device_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetag',
            name='icon',
            field=models.ImageField(upload_to='devicetag/'),
        ),
    ]
