# Generated by Django 4.0.7 on 2022-09-21 20:25

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_devicetag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetag',
            name='icon',
            field=sorl.thumbnail.fields.ImageField(upload_to='devicetag/'),
        ),
    ]
