# Generated by Django 4.0.5 on 2022-06-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_alter_devicestatus_options_device_building'),
        ('people', '0002_person_buildings_person_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceAccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('device_accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.deviceaccessory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
