# Generated by Django 4.0.5 on 2022-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='return_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='return_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
