# Generated by Django 4.0.5 on 2022-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_deviceaccessoryassignment_return_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='assignment_datetime',
            field=models.DateTimeField(verbose_name='assignment date'),
        ),
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='return_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='return date'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='assignment_datetime',
            field=models.DateTimeField(verbose_name='assignment date'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='return_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='return date'),
        ),
    ]
