# Generated by Django 4.0.5 on 2022-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_deviceaccessoryassignment_assignment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='return_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='return date'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='return_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='return date'),
        ),
    ]
