# Generated by Django 4.0.5 on 2022-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_deviceaccessoryassignment_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='assignment_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='assignment date'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='assignment_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='assignment date'),
        ),
    ]
