# Generated by Django 4.0.5 on 2022-08-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_devicemodel_unique_manufacturer_and_name'),
        ('people', '0011_person_primary_building_person_primary_room_and_more'),
        ('assignments', '0010_alter_deviceassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccessoryassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviceaccessoryassignments', to='people.person'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviceassignments', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviceassignments', to='people.person'),
        ),
    ]
