# Generated by Django 4.0.5 on 2022-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_buildings_person_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
