# Generated by Django 4.0.5 on 2022-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_persontype_is_inactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontype',
            name='is_inactive',
        ),
        migrations.AddField(
            model_name='personstatus',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
