# Generated by Django 4.0.5 on 2022-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_building_acronym_building_active_room_active'),
        ('people', '0003_alter_person_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='buildings',
            field=models.ManyToManyField(blank=True, to='locations.building'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='locations.room'),
        ),
    ]
