# Generated by Django 4.0.5 on 2022-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_buildings_alter_person_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='google_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
