# Generated by Django 4.0.5 on 2022-07-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_persontype_is_inactive'),
        ('people', '0007_alter_person_status'),
    ]

    operations = [
    ]
