# Generated by Django 4.0.5 on 2022-07-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_persontype_is_inactive_and_more'),
        ('people', '0008_merge_20220710_1917'),
    ]

    operations = [
    ]
