# Generated by Django 4.0.5 on 2022-07-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_merge_20220710_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
