# Generated by Django 4.0.5 on 2022-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleServiceAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='service_account', max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('private_key_id', models.CharField(max_length=255)),
                ('private_key', models.TextField(max_length=2048)),
                ('client_email', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_uri', models.CharField(default='https://accounts.google.com/o/oauth2/auth', max_length=255)),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('auth_provider_x09_cert_url', models.CharField(default='https://www.googleapis.com/oauth2/v1/certs', max_length=255)),
                ('client_x509_cert_url', models.CharField(max_length=255)),
            ],
        ),
    ]
