# Generated by Django 4.0.5 on 2022-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0003_googlepersonmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='matching_priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], unique=True),
        ),
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='person_field',
            field=models.CharField(choices=[('first_name', 'first name'), ('middle_name', 'middle name'), ('last_name', 'last name'), ('email', 'email'), ('internal_id', 'internal id'), ('type', 'type'), ('status', 'status')], max_length=255),
        ),
    ]
