# Generated by Django 4.0.5 on 2022-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0004_alter_googlepersonmapping_matching_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='matching_priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True),
        ),
    ]
