# Generated by Django 4.0.5 on 2022-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0005_alter_googlepersonmapping_matching_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='person_field',
            field=models.CharField(choices=[('first_name', 'first name'), ('middle_name', 'middle name'), ('last_name', 'last name'), ('email', 'email'), ('internal_id', 'internal id'), ('type', 'type'), ('status', 'status'), ('google_id', 'google id')], max_length=255),
        ),
    ]
