# Generated by Django 4.0.5 on 2022-06-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_google_id_alter_person_middle_name'),
        ('googlesync', '0006_alter_googlepersonmapping_person_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlepersonmapping',
            name='person_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='people.persontype'),
        ),
    ]
