# Generated by Django 4.0.5 on 2022-06-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_google_id_alter_person_middle_name'),
        ('googlesync', '0007_googlepersonmapping_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.persontype'),
        ),
    ]
