# Generated by Django 4.0.5 on 2022-06-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0008_alter_googlepersonmapping_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleserviceaccountconfig',
            name='delegate',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
