# Generated by Django 4.0.5 on 2022-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0010_googleserviceaccountconfig_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='delegate',
            field=models.EmailField(help_text='User account to impersonate when accessing Google. User must have rights to the resources needed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='target',
            field=models.CharField(help_text='Google domain name to connect to (e.g. my.site.com)', max_length=255),
        ),
    ]
