# Generated by Django 4.0.5 on 2022-06-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_person_status'),
        ('googlesync', '0011_alter_googleserviceaccountconfig_delegate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePersonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_field', models.CharField(choices=[('first_name', 'first name'), ('middle_name', 'middle name'), ('last_name', 'last name'), ('email', 'email'), ('internal_id', 'internal id'), ('type', 'type'), ('status', 'status'), ('google_id', 'google id')], max_length=255)),
                ('translate_from', models.CharField(max_length=255)),
                ('translate_to', models.CharField(max_length=255)),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.persontype')),
            ],
        ),
    ]
