# Generated by Django 4.0.5 on 2022-06-27 14:20

from email.policy import default
from django.db import migrations, models
import django.db.models.deletion

def create_google_person_sync_profile(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    GooglePersonSyncProfile = apps.get_model('googlesync', 'GooglePersonSyncProfile')
    GoogleServiceAccountConfig = apps.get_model('googlesync','GoogleServiceAccountConfig')
    PersonType = apps.get_model('people','PersonType')
    g = GooglePersonSyncProfile(
        name="staff", 
        google_service_account_config = GoogleServiceAccountConfig.objects.get(pk=1),
        person_type = PersonType.objects.get(name="Staff"),
    )
    g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_person_status'),
        ('googlesync', '0012_googlepersontranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlepersonmapping',
            name='person_type',
        ),
        migrations.RemoveField(
            model_name='googlepersontranslation',
            name='person_type',
        ),
        migrations.CreateModel(
            name='GooglePersonSyncProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_service_account_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='googlesync.googleserviceaccountconfig')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.persontype')),
            ],
        ),
        migrations.RunPython(create_google_person_sync_profile),
        
        migrations.AddField(
            model_name='googlepersonmapping',
            name='google_person_sync_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='googlesync.googlepersonsyncprofile'),
            
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlepersontranslation',
            name='google_person_sync_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='googlesync.googlepersonsyncprofile'),
            preserve_default=False,
        ),
    ]
