# Generated by Django 4.0.5 on 2022-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0013_remove_googlepersonmapping_person_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlepersonsyncprofile',
            name='google_query',
            field=models.CharField(default='orgUnitPath=/', help_text="Google API query to use when searching for users to sync for this profile. (e.g. 'orgUnitPath=/Staff')", max_length=1024),
        ),
    ]
