# Generated by Django 4.0.5 on 2022-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0016_remove_googlepersontranslation_google_person_sync_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlepersonsyncprofile',
            name='google_query',
            field=models.CharField(default='orgUnitPath=/', help_text="Google API query to use when searching for users to sync for this profile. (e.g. 'orgUnitPath=/Staff'). Query documentation: https://developers.google.com/admin-sdk/directory/v1/guides/search-users", max_length=1024),
        ),
    ]
