# Generated by Django 4.0.5 on 2022-06-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0017_alter_googlepersonsyncprofile_google_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_field', models.CharField(max_length=255)),
                ('device_field', models.CharField(choices=[('serial_number', 'serial number'), ('asset_id', 'asset id'), ('notes', 'notes'), ('status', 'status'), ('google_id', 'google id'), ('google_status', 'google status'), ('google_organization_unit', 'google organization unit'), ('google_enrollment_time', 'google enrollment time'), ('google_last_policy_sync', 'google last policy sync'), ('google_location', 'google location'), ('google_most_recent_user', 'google most recent user'), ('device_model', 'device model'), ('building', 'building'), ('room', 'room')], max_length=255)),
                ('matching_priority', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='googlepersonsyncprofile',
            name='google_query',
            field=models.CharField(blank=True, default='orgUnitPath=/', help_text="Google API query to use when searching for users to sync for this profile. (e.g. 'orgUnitPath=/Staff'). Query documentation: https://developers.google.com/admin-sdk/directory/v1/guides/search-users", max_length=1024),
        ),
        migrations.CreateModel(
            name='GoogleDeviceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_from', models.CharField(max_length=255)),
                ('translate_to', models.CharField(max_length=255)),
                ('google_device_mapping', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='googlesync.googledevicemapping')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDeviceSyncProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_org_unit_path', models.CharField(blank=True, default='', help_text='The full path of the organizational unit (minus the leading /) or its unique ID.', max_length=1024)),
                ('google_query', models.CharField(blank=True, default='', help_text="Google API query to use when searching for devices to sync for this profile. (e.g. 'location:seattle'). Query documentation: https://developers.google.com/admin-sdk/directory/v1/list-query-operators", max_length=1024)),
                ('google_service_account_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='googlesync.googleserviceaccountconfig')),
            ],
        ),
        migrations.AddField(
            model_name='googledevicemapping',
            name='google_device_sync_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='googlesync.googledevicesyncprofile'),
        ),
    ]
