# Generated by Django 4.0.5 on 2022-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0021_alter_googledevicemapping_device_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDevice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('organization_unit', models.CharField(blank=True, max_length=255)),
                ('enrollment_time', models.DateTimeField(blank=True, null=True)),
                ('last_policy_sync', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('most_recent_user', models.CharField(blank=True, max_length=255)),
                ('annotated_asset_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='googledevicemapping',
            name='device_field',
            field=models.CharField(choices=[('serial_number', 'serial number'), ('asset_id', 'asset id'), ('notes', 'notes'), ('status', 'status'), ('device_model', 'device model'), ('building', 'building'), ('room', 'room'), ('google_device', 'google device')], max_length=255),
        ),
    ]
