# Generated by Django 4.0.5 on 2022-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0022_googledevice_alter_googledevicemapping_device_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
