# Generated by Django 4.0.5 on 2022-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0023_googledevice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleconfig',
            name='auth_provider_x09_cert_url',
            field=models.URLField(default='https://www.googleapis.com/oauth2/v1/certs', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleconfig',
            name='auth_uri',
            field=models.URLField(default='https://accounts.google.com/o/oauth2/auth', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleconfig',
            name='token_uri',
            field=models.URLField(default='https://oauth2.googleapis.com/token', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='auth_provider_x09_cert_url',
            field=models.URLField(default='https://www.googleapis.com/oauth2/v1/certs', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='auth_uri',
            field=models.URLField(default='https://accounts.google.com/o/oauth2/auth', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='token_uri',
            field=models.URLField(default='https://oauth2.googleapis.com/token', max_length=255),
        ),
    ]
