# Generated by Django 4.0.5 on 2022-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0024_alter_googleconfig_auth_provider_x09_cert_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleconfig',
            old_name='auth_provider_x09_cert_url',
            new_name='auth_provider_x509_cert_url',
        ),
        migrations.RenameField(
            model_name='googleserviceaccountconfig',
            old_name='auth_provider_x09_cert_url',
            new_name='auth_provider_x509_cert_url',
        ),
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='client_x509_cert_url',
            field=models.URLField(max_length=255),
        ),
    ]
