# Generated by Django 4.0.5 on 2022-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0026_remove_googledevicemapping_unique_google_device_sync_profile_and_device_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleserviceaccountconfig',
            name='client_email',
            field=models.EmailField(max_length=255),
        ),
    ]
