# Generated by Django 4.0.5 on 2022-07-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0027_alter_googleserviceaccountconfig_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevicemapping',
            name='sync_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='googlesync.googledevicesyncprofile'),
        ),
        migrations.AlterField(
            model_name='googledevicetranslation',
            name='google_device_mapping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='googlesync.googledevicemapping'),
        ),
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='sync_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='googlesync.googlepersonsyncprofile'),
        ),
        migrations.AlterField(
            model_name='googlepersontranslation',
            name='google_person_mapping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='googlesync.googlepersonmapping'),
        ),
    ]
