# Generated by Django 4.0.5 on 2022-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0028_alter_googledevicemapping_sync_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevicemapping',
            name='to_field',
            field=models.CharField(choices=[('serial_number', 'serial number'), ('device_model', 'device model'), ('status', 'status'), ('organization_unit', 'organization unit'), ('enrollment_time', 'enrollment time'), ('last_policy_sync', 'last policy sync'), ('location', 'location'), ('most_recent_user', 'most recent user'), ('annotated_asset_id', 'annotated asset id')], max_length=255),
        ),
    ]
