# Generated by Django 4.0.5 on 2022-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0030_alter_googledevice_last_policy_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='annotated_asset_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='enrollment_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='most_recent_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='organization_unit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
