# Generated by Django 4.0.5 on 2022-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0032_alter_googledevicemapping_to_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
