# Generated by Django 4.0.5 on 2022-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0033_alter_googledevice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='annotated_asset_id',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
