# Generated by Django 4.0.5 on 2022-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0037_alter_googledevice_annotated_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='annotated_asset_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
