# Generated by Django 4.0.5 on 2022-07-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0038_alter_googledevice_annotated_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='device_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='most_recent_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='organization_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googledevice',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
