# Generated by Django 4.0.5 on 2022-07-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0039_alter_googledevice_device_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDeviceLinkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_priority', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True)),
                ('from_field', models.CharField(choices=[('serial_number', 'serial number'), ('device_model', 'device model'), ('status', 'status'), ('organization_unit', 'organization unit'), ('enrollment_time', 'enrollment time'), ('last_policy_sync', 'last policy sync'), ('location', 'location'), ('most_recent_user', 'most recent user'), ('annotated_asset_id', 'annotated asset id')], max_length=255)),
                ('to_field', models.CharField(choices=[('serial_number', 'serial number'), ('asset_id', 'asset id'), ('notes', 'notes'), ('status', 'status'), ('device_model', 'device model'), ('building', 'building'), ('room', 'room'), ('google_device', 'google device')], max_length=255)),
                ('sync_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_mappings', to='googlesync.googledevicesyncprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='googledevicelinkmapping',
            constraint=models.UniqueConstraint(fields=('sync_profile', 'to_field'), name='unique_sync_profile_and_to_field_in_googledevicelinkmapping'),
        ),
    ]
