# Generated by Django 4.0.5 on 2022-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0040_googledevicelinkmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevicelinkmapping',
            name='matching_priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='googledevicemapping',
            name='matching_priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='googlepersonmapping',
            name='matching_priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AddConstraint(
            model_name='googledevicelinkmapping',
            constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='unique_sync_profile_and_matching_priority_in_googledevicelinkmapping'),
        ),
        migrations.AddConstraint(
            model_name='googledevicemapping',
            constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='unique_sync_profile_and_matching_priority_in_googledevicemapping'),
        ),
        migrations.AddConstraint(
            model_name='googlepersonmapping',
            constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='unique_sync_profile_and_matching_priority_in_googlepersonmapping'),
        ),
    ]
