# Generated by Django 4.0.5 on 2022-07-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0042_googlepersonsyncprofile_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCustomSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('etag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='googleserviceaccountconfig',
            name='person_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GoogleCustomSchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_id', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('multi_valued', models.BooleanField()),
                ('kind', models.CharField(max_length=255)),
                ('etag', models.CharField(max_length=255)),
                ('indexed', models.BooleanField()),
                ('display_name', models.CharField(max_length=255)),
                ('read_access_type', models.CharField(max_length=255)),
                ('numeric_indexing_spec_min_value', models.IntegerField()),
                ('numeric_indexing_spec_max_value', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlesync.googlecustomschema')),
            ],
        ),
        migrations.AddField(
            model_name='googlecustomschema',
            name='service_account_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='googlesync.googleserviceaccountconfig'),
        ),
    ]
