# Generated by Django 4.0.5 on 2022-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0042_googlepersonsyncprofile_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlepersonsyncprofile',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
