# Generated by Django 4.0.5 on 2022-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0043_googlecustomschema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecustomschemafield',
            name='numeric_indexing_spec_max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecustomschemafield',
            name='numeric_indexing_spec_min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
