# Generated by Django 4.0.5 on 2022-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0044_alter_googlecustomschemafield_numeric_indexing_spec_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecustomschemafield',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='googlecustomschemafield',
            name='multi_valued',
            field=models.BooleanField(default=False),
        ),
    ]
