# Generated by Django 4.0.5 on 2022-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0047_alter_googledefaultschema_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googledefaultschemaproperty',
            options={'verbose_name_plural': 'Google default schema properties'},
        ),
        migrations.AlterField(
            model_name='googledefaultschemaproperty',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
