# Generated by Django 4.0.5 on 2022-07-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0048_alter_googledefaultschemaproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledefaultschemaproperty',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
