# Generated by Django 4.0.5 on 2022-08-01 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0049_alter_googledefaultschemaproperty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledefaultschemaproperty',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='googlesync.googledefaultschema'),
        ),
    ]
