# Generated by Django 4.0.5 on 2022-08-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0050_alter_googledefaultschemaproperty_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledefaultschemaproperty',
            name='ref',
        ),
        migrations.AddField(
            model_name='googledefaultschemaproperty',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='googlesync.googledefaultschemaproperty'),
        ),
        migrations.AlterField(
            model_name='googledefaultschemaproperty',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='googlesync.googledefaultschema'),
        ),
    ]
