# Generated by Django 4.0.5 on 2022-08-01 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0053_remove_googledevicemapping_from_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlepersonmapping',
            name='from_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='googlesync.googledefaultschemaproperty'),
        ),
    ]
