# Generated by Django 4.0.5 on 2022-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0054_googlepersonmapping_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledefaultschemaproperty',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
