# Generated by Django 4.0.5 on 2022-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0056_googledevicemapping_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleserviceaccountconfig',
            name='device_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
