# Generated by Django 4.0.5 on 2022-08-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0058_rename_from_field_googledevicemapping_from_field_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledevicemapping',
            name='from_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='googlesync.googledefaultschemaproperty'),
        ),
    ]
