# Generated by Django 4.0.5 on 2022-08-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0059_googledevicemapping_from_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledevicemapping',
            name='from_field_old',
        ),
        migrations.AlterField(
            model_name='googledevicemapping',
            name='from_field',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('schema__schema_id', 'ChromeOsDevice')), null=True, on_delete=django.db.models.deletion.PROTECT, to='googlesync.googledefaultschemaproperty'),
        ),
    ]
