# Generated by Django 4.0.5 on 2022-08-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_room_unique_room_per_building'),
        ('googlesync', '0061_alter_googlepersonmapping_to_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBuildingToOUMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ou', models.CharField(max_length=1024)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.building')),
            ],
        ),
    ]
