# Generated by Django 4.0.5 on 2022-08-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_room_unique_room_per_building'),
        ('googlesync', '0062_devicebuildingtooumapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceBuildingToOUMapping',
            new_name='DeviceBuildingToGoogleOUMapping',
        ),
    ]
