# Generated by Django 4.0.5 on 2022-08-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0063_rename_devicebuildingtooumapping_devicebuildingtogoogleoumapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicebuildingtogoogleoumapping',
            old_name='ou',
            new_name='organization_unit',
        ),
    ]
