# Generated by Django 4.0.5 on 2022-08-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_person_primary_building_person_primary_room_and_more'),
        ('googlesync', '0064_rename_ou_devicebuildingtogoogleoumapping_organization_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebuildingtogoogleoumapping',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.persontype'),
        ),
    ]
