# Generated by Django 4.0.5 on 2022-08-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0002_googleserviceaccountconfig'),
        ('googlesync', '0003_googlepersonmapping'),
        ('googlesync', '0004_alter_googlepersonmapping_matching_priority_and_more'),
        ('googlesync', '0065_devicebuildingtogoogleoumapping_person_type'),
    ]

    operations = [
    ]
