# Generated by Django 4.0.5 on 2022-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googlesync", "0066_merge_20220803_1351"),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #    model_name='googledevicelinkmapping',
        #    name='unique_sync_profile_and_to_field_in_googledevicelinkmapping',
        # ),
        # migrations.RemoveConstraint(
        #    model_name="googledevicelinkmapping",
        #    name="unique_sync_profile_and_matching_priority_in_googledevicelinkmapping",
        # ),
        ## migrations.RemoveConstraint(
        ##    model_name='googledevicemapping',
        ##    name='unique_sync_profile_and_to_field_in_googledevicemapping',
        ## ),
        # migrations.RemoveConstraint(
        #    model_name="googledevicemapping",
        #    name="unique_sync_profile_and_matching_priority_in_googledevicemapping",
        # ),
        ## migrations.RemoveConstraint(
        ##    model_name='googlepersonmapping',
        ##    name='unique_sync_profile_and_to_field_in_googlepersonmapping',
        ## ),
        # migrations.RemoveConstraint(
        #    model_name="googlepersonmapping",
        #    name="unique_sync_profile_and_matching_priority_in_googlepersonmapping",
        # ),
        migrations.AddConstraint(
            model_name="googledevicelinkmapping",
            constraint=models.UniqueConstraint(
                fields=("sync_profile", "to_field"),
                name="u_sync_profile_and_to_field_googledevicelinkmapping",
            ),
        ),
        # migrations.AddConstraint(
        #    model_name='googledevicelinkmapping',
        #    constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='u_sync_profile_and_matching_priority_googledevicelinkmapping'),
        # ),
        migrations.AddConstraint(
            model_name="googledevicemapping",
            constraint=models.UniqueConstraint(
                fields=("sync_profile", "to_field"),
                name="u_sync_profile_and_to_field_googledevicemapping",
            ),
        ),
        # migrations.AddConstraint(
        #    model_name='googledevicemapping',
        #    constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='u_sync_profile_and_matching_priority_googledevicemapping'),
        # ),
        migrations.AddConstraint(
            model_name="googlepersonmapping",
            constraint=models.UniqueConstraint(
                fields=("sync_profile", "to_field"),
                name="u_sync_profile_and_to_field_googlepersonmapping",
            ),
        ),
        # migrations.AddConstraint(
        #    model_name='googlepersonmapping',
        #    constraint=models.UniqueConstraint(fields=('sync_profile', 'matching_priority'), name='u_sync_profile_and_matching_priority_googlepersonmapping'),
        # ),
    ]
