# Generated by Django 4.0.5 on 2022-08-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0068_remove_googledevicelinkmapping_unique_sync_profile_and_to_field_in_googledevicelinkmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecustomschemafield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='googlesync.googlecustomschema'),
        ),
    ]
