# Generated by Django 4.0.5 on 2022-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesync', '0069_alter_googlecustomschemafield_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
